apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DB_NAME: "bookstore"
  FRONTEND_URL: "http://localhost:3000"