name: CI/CD Pipeline

on:
  push:
    branches:
      - devops

jobs:
  build-scan-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./bookstore-main
          file: ./bookstore-main/client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ashrafbilalmohaidat/bookstore-frontend:latest
            ashrafbilalmohaidat/bookstore-frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./bookstore-main
          file: ./bookstore-main/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ashrafbilalmohaidat/bookstore-backend:latest
            ashrafbilalmohaidat/bookstore-backend:${{ github.sha }}

      - name: Scan frontend image
        shell: powershell
        run: docker run --rm aquasecurity/trivy-action@0.33.1 image --severity HIGH,CRITICAL --exit-code 0 --ignore-unfixed=false --vuln-type os,library --format table ashrafbilalmohaidat/bookstore-frontend:latest

      - name: Scan backend image
        shell: powershell
        run: docker run --rm aquasecurity/trivy-action@0.33.1 image --severity HIGH,CRITICAL --exit-code 0 --ignore-unfixed=false --vuln-type os,library --format table ashrafbilalmohaidat/bookstore-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build-scan-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update frontend image in manifest
        shell: powershell
        run: |
          (Get-Content k8s/frontend/deployment.yaml) `
            -replace 'image: ashrafbilalmohaidat/bookstore-frontend:.*',
                    "image: ashrafbilalmohaidat/bookstore-frontend:${{ github.sha }}" `
            | Set-Content k8s/frontend/deployment.yaml

      - name: Update backend image in manifest
        shell: powershell
        run: |
          (Get-Content k8s/backend/deployment.yaml) `
            -replace 'image: ashrafbilalmohaidat/bookstore-backend:.*',
                    "image: ashrafbilalmohaidat/bookstore-backend:${{ github.sha }}" `
            | Set-Content k8s/backend/deployment.yaml


      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s/namespaces/namespaces.yaml
          kubectl apply -f k8s/mongodb/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/frontend/
          kubectl rollout restart deployment/frontend -n production
          kubectl rollout restart deployment/backend -n production