name: CI/CD Pipeline

on:
  push:
    branches:
      - devops

jobs:
  build-scan-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./bookstore-main
          file: ./bookstore-main/client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ashrafbilalmohaidat/bookstore-frontend:latest
            ashrafbilalmohaidat/bookstore-frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./bookstore-main
          file: ./bookstore-main/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ashrafbilalmohaidat/bookstore-backend:latest
            ashrafbilalmohaidat/bookstore-backend:${{ github.sha }}

      - name: Install Trivy
        run: |
          choco install trivy -y

      - name: Scan frontend image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL ashrafbilalmohaidat/bookstore-frontend:latest

      - name: Scan backend image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL ashrafbilalmohaidat/bookstore-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build-scan-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update frontend image in manifest
        run: |
          sed -i "s|image: bookstore-client:.*|image: ashrafbilalmohaidat/bookstore-frontend:${{ github.sha }}|g" bookstore-main/k8s/frontend/deployment.yaml

      - name: Update backend image in manifest
        run: |
          sed -i "s|image: bookstore-server:.*|image: ashrafbilalmohaidat/bookstore-backend:${{ github.sha }}|g" bookstore-main/k8s/backend/deployment.yaml

      - name: Deploy to minikube
        run: |
          kubectl apply -f bookstore-main/k8s/namespaces/namespaces.yaml
          kubectl apply -f bookstore-main/k8s/mongodb/
          kubectl apply -f bookstore-main/k8s/backend/
          kubectl apply -f bookstore-main/k8s/frontend/
          kubectl rollout restart deployment/frontend -n production
          kubectl rollout restart deployment/backend -n production